# Generated by Django 4.1.1 on 2022-09-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_members_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='email',
            field=models.EmailField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='members',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
