# Generated by Django 4.1.1 on 2022-09-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_members_email_alter_members_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
